definitions:
  authentication_service.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  authentication_service.Profile:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
      password:
        type: string
      role:
        type: string
      updated_at:
        type: string
    type: object
  reservation_service.AddRestaurantRequest:
    properties:
      address:
        type: string
      description:
        type: string
      name:
        type: string
      phone_number:
        type: string
    type: object
  reservation_service.UpdateRestaurantRequest:
    properties:
      address:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      phone_number:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server for a restaurant reservation system.
  title: Restaurant Reservation System API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: User inserts their credentials like email and password
      parameters:
      - description: example@gmail.com
        in: body
        name: LoginRequest
        required: true
        schema:
          $ref: '#/definitions/authentication_service.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login and Getting Token
      tags:
      - Authentication
  /auth/profile/{id}:
    get:
      consumes:
      - application/json
      description: Retrieve user profile information using user ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get profile by ID
      tags:
      - Profile
  /auth/register:
    post:
      consumes:
      - application/json
      description: User inserts their credentials
      parameters:
      - description: registering
        in: body
        name: profile
        required: true
        schema:
          $ref: '#/definitions/authentication_service.Profile'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register user with credentials
      tags:
      - Authentication
  /restaurant/:
    get:
      consumes:
      - application/json
      description: Geting all restaurant
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all restaurant
      tags:
      - Restaurant
    post:
      consumes:
      - application/json
      description: Adding new restaurant
      parameters:
      - description: Creating new restaurnat
        in: body
        name: AddRestaurantRequest
        required: true
        schema:
          $ref: '#/definitions/reservation_service.AddRestaurantRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Add new restaurant
      tags:
      - Restaurant
  /restaurant/{id}:
    delete:
      consumes:
      - application/json
      description: Delete restaurant information using restaurant ID
      parameters:
      - description: Restaurant ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Delete restaurant by ID
      tags:
      - Restaurant
    get:
      consumes:
      - application/json
      description: Get restaurant information using restaurant ID
      parameters:
      - description: Restaurant ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get restaurant by ID
      tags:
      - Restaurant
    put:
      consumes:
      - application/json
      description: Update restaurant information using restaurant ID
      parameters:
      - description: Restaurant ID
        in: path
        name: id
        required: true
        type: string
      - description: Updating restaurant
        in: body
        name: UpdateRestaurantRequest
        required: true
        schema:
          $ref: '#/definitions/reservation_service.UpdateRestaurantRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update restaurant by ID
      tags:
      - Restaurant
swagger: "2.0"
